# Generated by Django 5.1 on 2024-08-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('classe', models.CharField(max_length=45)),
                ('raca', models.CharField(max_length=45)),
                ('pontos_de_vida', models.CharField(max_length=45)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador')),
            ],
        ),
    ]
