# Generated by Django 5.1 on 2024-08-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='pontos_de_vida',
        ),
        migrations.AddField(
            model_name='jogador',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='app.jogador'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.CharField(max_length=50),
        ),
    ]
