# Generated by Django 5.1 on 2024-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jogador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='raca',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
