# Generated by Django 5.1 on 2024-08-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_personagem_raca_alter_jogador_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='habilidades',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personagem',
            name='raca',
            field=models.CharField(default='Human', max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(max_length=100),
        ),
    ]
