# Generated by Django 5.1 on 2024-08-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personagem_habilidades_personagem_raca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='raca',
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(max_length=50),
        ),
    ]
